version: "3.7"
services: 
  db:
    image: postgres
    environment: 
      POSTGRES_DB: varoliletisim
      POSTGRES_PASSWORD: crossmyheart1243
      POSTGRES_USER: postgres
    volumes: 
      - ./postgres_vol:/var/lib/postgresql/data
    ports: 
      - '5432:5432'
  web:
    image: varoliletisim/node_server
    depends_on:
      - db
    ports: 
      - "8080:8080"
    # if server and database run successfuly, delete this and the below 2 lines, it means that .env get's automatically loaded.
    # env_file: 
    #   - .env